### ISSUE TITLE
Favicons should be added with a hash

### ISSUE THREAD

**Issue by kirill-konshin** [ampedandwired/html-webpack-plugin#129]
Currently the generated markup is as follows:

```html
<link rel="shortcut icon" href="/favicon.ico">
```

Suggested markup is:

```html
<link rel="icon" type="image/x-icon" href="/favicon.ico?xxx">
<link rel="shortcut icon" type="image/x-icon" href="/favicon.ico?xxx">
<link rel="shortcut" type="image/x-icon" href="/favicon.ico?xxx">
```

**Comment by D1plo1d** [comment]
Being able to load it as `favicon.[hash].png` would also be helpful for me. Maybe something similar to how you can configure output filenames?

Eg.

```javascript
      new HtmlWebpackPlugin({
        favicon: {
          source: 'images/icon.png',
          outputFilename: 'icon.[hash].png'
        },
      }),
```

**Comment by laszlokorte** [comment]
It would be great if the the the output favicon name could differ from the original name of the file. Eg I have multiple entry points like:
```
[
new HtmlWebpackPlugin({
      title: 'Home',
      minify: htmlMinifyOptions,
      chunks: ['home', 'vendor'],
      template: './app/index.html',
      filename: 'index.html',
      favicon: './app/pages/home/favicon.ico',
    }),
    new HtmlWebpackPlugin({
      title: 'Contact',
      minify: htmlMinifyOptions,
      chunks: ['contact', 'vendor'],
      template: './app/index.html',
      filename: 'contact.html',
      favicon: './app/pages/contact/favicon.ico',
    }),
]
```

I would like to have different favicons for the home page and the contact page but I would like to have the original favicon files to be named favicon (`./app/pages/home/favicon.ico` and `./app/pages/contact/favicon.ico`). Currently this is not working because their both output names will just be `favicon.ico` and they will conflict. Having the file's hash in the output name would solve this.

**Comment by jantimon** [comment]
Please use the https://github.com/jantimon/favicons-webpack-plugin for advanced favicon options.

**Comment by gwiant** [comment]
No "theme_color" in output manifest.json.  I don't see any info on configuring options other than ver simple example.  output manifest.json is invalid due to this.
