### ISSUE TITLE
Order of scripts

### ISSUE THREAD

**Issue by kampdomoj** [ampedandwired/html-webpack-plugin#140]
I am creating 3 bundles and need to be able to insert them in a specific order:

This is what is generated:
```
<script src="common.8eab23e9e55f8c47699c.bundle.js"></script>
<script src="app.8eab23e9e55f8c47699c.bundle.js"></script>
<script src="angular2.8eab23e9e55f8c47699c.bundle.js"></script></body>
```
but I need to have my app.bundle as the last one.

My config is:
```
module.exports = {
    entry: {
        "angular2": [
            "core-js",
            "rxjs",
            "zone.js",
            "reflect-metadata",
            "angular2/angular2",
            "angular2/core",
            "angular2/router",
            "angular2/http"
        ],
        "app": "./src/app/bootstrap.ts" // our app
    },
    output: {
        path: root('__build__'),
        filename: '[name].[hash].bundle.js',
        chunkFilename: '[id].chunk.js'
    },
    plugins: [
        new CommonsChunkPlugin('angular2', '[name].[hash].bundle.js'),
        new CommonsChunkPlugin('common', '[name].[hash].bundle.js'),
        new HtmlWebpackPlugin({
            template: './src/public/index.html',
            inject: 'body',
            minify: false
        })
    ],
```

**Comment by jantimon** [comment]
You can write a custom sort function:

https://github.com/ampedandwired/html-webpack-plugin/blob/master/index.js#L176

**Comment by jantimon** [comment]
@kampdomoj can this be closed?

**Comment by kampdomoj** [comment]
The thing is that I am a javascript newbie, so I need an example to be able to test this. I have been googling on chunkSortMode to find one, but apparently nobody published a custom sort function that I can use as a starting point... :(

**Comment by jantimon** [comment]
The default chunkSortMode function is this one:
```js
(function orderEntryLast(a, b) {
      if (a.entry !== b.entry) {
        return b.entry ? 1 : -1;
      } else {
        return b.id - a.id;
      }
    })
```

Use https://github.com/s-a/iron-node with debugger or console.log to get the details for a and b

**Comment by ruehl** [comment]
I'm probably a bit late, but maybe someone else finds this helpful. In order to get the correct bundle order, you should set chunksSortMode to 'none' and add Webpack's OccurrenceOrderPlugin to Webpack's configuration. Given @kampdomoj Angular 2 setup, I would suggest something like

```
plugins: [
        new OccurenceOrderPlugin(true),
        new CommonsChunkPlugin({
            name: 'angular2',
            filename: 'angular2.js',
            minChunks: Infinity
        }),
        new CommonsChunkPlugin({
            name: 'common',
            filename: 'common.js'
        }),
        new HtmlWebpackPlugin({
            filename: '../index.html',
            hash: false,
            template: config.sourcePath + '/index.html',
            inject: 'body',
            chunksSortMode: 'none'
        })
    ];
```
This should result in the proper bundle order without using a custom sorter function.

**Comment by jantimon** [comment]
@ruehl thanks for the information
could you please go a little bit in detail and explain how the OccurrenceOrderPlugin might help here?

**Comment by ruehl** [comment]
@jantimon Actually, it is more of a crude workaround than a real solution. The OOP rearranges order of modules (and therefore implicitly chunks as well) by their link counter. Due to the nature of Angular2 setup common.js is most often linked, followed by angular2.js followed by app.js, thus resulting in a working structure.

Only my 2 cents and being a Webpack rookie: after fiddling around with the sort function (chunkSortMode) and inspecting the arguments passed to that function, I wonder if it wouldn't be an option to sort chunks by their parent relationship rather than by their individual ids: if module A is listed as parent of B, then A should be embedded before B. Or more general: if module A is an ancestor (ie. parent of grade N) of module B, then A should be embedded for B. So basically we would perform a topological sort on the dependency graph of the chunks. Of course this would not work on graphs including one or more dependency cycles.

What are your thoughts on such an approach?

**Comment by jantimon** [comment]
I haven't looked into the sorting of the chunks at all. But your suggestion sounds like it would for almost every thinkable use case. Feel free to open a pull request :)

**Comment by ruehl** [comment]
Then I'm looking forward my first pull request on Github ever ;-)

**Comment by daggerok** [comment]
don't understand why, but ruehl's solution works

**Comment by Guedez** [comment]
This one worked for me
`
				chunksSortMode: function(a, b) {
					var order = ["polyfills", "libs", "js", "vendor", "main"];
					return order.indexof(b.names[0]) - order.indexof(a.names[0]);
				}
`

for reference, my entries is 

`
		entry: {
			'libs': ['./src/js/util.js',
				'./src/libs/RSA/rsa_compiled.js',
				'./src/libs/forge.min.0.6.12.js',
				'./src/libs/FileSaver.js',
				'./src/libs/DataStream.js',
				'./src/libs/pako.js',
				'./src/libs/lodash.core.js'
			],
			'js': ['./src/js/server_message.js',
				'./src/js/messages/files.js', './src/js/messages/login.js', './src/js/messages/tabs.js',
				'./src/js/message_decoder.js', './src/js/message_encoder.js'
			],
			'polyfills': './src/polyfills.browser.ts',
			'vendor': './src/vendor.browser.ts',
			'main': './src/main.browser.ts',
		},
`.

**Comment by jperasmus** [comment]
@Guedez solution worked for me as well, I just had to swap around `b.names[0]` and `a.names[0]` and make it `indexOf` instead of `indexof`. Thank you for the share!

**Comment by daggerok** [comment]
worked solution for webpack 2

```javascript
...
entry: {
  vendors: [
    './src/polyfills.ts',
    './src/vendors.ts',
  ],
  app: './src/main.ts',
},
...
plugins: {
  ...
  new CommonsChunkPlugin({
    name: 'vendors',
    ...
  }),
  new HtmlWebpackPlugin({
    chunks: [
      'vendors',
      'app',
    ],
  }),
  ...
},
```

**Comment by jantimon** [comment]
@Nek- this is also possible using `chunkSortMode: 'manual'`.

**Comment by aboutqx** [comment]
@jantimon thanks,but it's `chunksSortMode`  with a `s`.
