### ISSUE TITLE
Is it possible to replace filenames with chunks in a jinja.html template?

### ISSUE THREAD

**Issue by qmmr** [ampedandwired/html-webpack-plugin#290]
I couldn't find anything that would work for me out of the box for jinja templates (Django). Is there any chance to request such feature in html-webpack-plugin?
Currently I'm using gulp-rev and gulp-rev-replace. I'm new to webpack ecosystem so forgive me if this question does not make any sense.

Best, Marcin

**Comment by jantimon** [comment]
Do you want to generate django templates or do you want to reuse django templates?

**Comment by qmmr** [comment]
@jantimon reuse, I've got a script in the template like
```django
<script type="text/javascript" src="{{ static_url_for('js/main.js') }}"></script>
```
and I want simply to replace `main.js` with `main-[chunkhash].js`

**Comment by jantimon** [comment]
So you want to pass a file generated by django to the plugin or do you want to generate a file which you will be picked up by django?

**Comment by qmmr** [comment]
@jantimon I want to pass a generated file and as an output I want to have the same file with `main.js` from my prev example replaced with `main.adsfad9fa07fad0f7.js`.

**Comment by jantimon** [comment]
Okay I asked twice but didn't understand the answer.
The html-webpack-plugin lets you generate templates too.
If you just need `<script type="text/javascript" src="{{ static_url_for('js/main.js') }}"></script>`  instead of `<script type="text/javascript" src="js/main.js"></script>` you can turn off the inject feature by setting `inject:false` and design the template by your own like in the following example:

https://github.com/jaketrent/html-webpack-template/blob/86f285d5c790a6c15263f5cc50fd666d51f974fd/index.html
