### ISSUE TITLE
Cannot read property 'hash' of undefined

### ISSUE THREAD

**Issue by prescottprue** [ampedandwired/html-webpack-plugin#342]
I am receiving the following error when upgrading from `1.7.0`. Read the upgrade guide and everything.

```
/Users/scott.prue/code/node_modules/html-webpack-plugin/lib/compiler.js:73
        hash: childCompilation.hash,
                              ^
TypeError: Cannot read property 'hash' of undefined
    at /Users/scott.prue/code/node_modules/html-webpack-plugin/lib/compiler.js:73:31
    at Compiler.<anonymous> (/Users/scott.prue/code/node_modules/webpack/lib/Compiler.js:204:18)
    at Compiler.<anonymous> (/Users/scott.prue/code/node_modules/webpack/lib/Compiler.js:395:18)
    at/Users/scott.prue/code/node_modules/tapable/lib/Tapable.js:99:11
    at Compilation.<anonymous> (/Users/scott.prue/code/node_modules/webpack/lib/Compilation.js:433:1
```

**Comment by jantimon** [comment]
Oh - could you please add `console.log(arguments)` here:

https://github.com/ampedandwired/html-webpack-plugin/blob/master/lib/compiler.js#L71

I guess its a uncached error.

**Comment by wmartins** [comment]
Hey @prescottprue, I am having the same issue here, did you find any solution for that?

**Comment by wmartins** [comment]
@prescottprue, using @jantimon tip I realised that I was using `let` inside my templates, instead of `var`, producing the following error:

`ModuleBuildError: Module build failed: SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode`

Previous template:

```<% for (let css in htmlWebpackPlugin.files.css) { %>```

I think it would be a good idea to try to catch those kind of errors and throw them to the console, so it is easier to see what's going on.

**Comment by thymikee** [comment]
@jantimon I see that the error is properly handled on `master` branch. Any chances for a patch release? `2.20.1` or something.
Thanks!
