### ISSUE TITLE
Question: How do I inject scripts to head & body

### ISSUE THREAD

**Issue by thevangelist** [ampedandwired/html-webpack-plugin#381]
I am using New Relic for monitoring, and my current bundle.js goes to body.

How can I inject my NR script to head?

```    
new HtmlWebpackPlugin({
   template: 'src/index.tpl.html',
   inject: 'body',
   filename: 'index.html',
   favicon: 'src/images/favicon.png'
})
```
```
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
  <body>
    <div id="root"></div>
  </body>
</html>
```

**Comment by antoligy** [comment]
You should be able to specify `inject` as `head`, does that work?

**Comment by jantimon** [comment]
why do you need to inject it instead of just adding it to the template?

**Comment by niekoost** [comment]
I think that @thevangelist needs to inject the New Relic script for browser monitoring into the head of the index.html, while references to the generated bundles need to go into the body. 

When you use different git branches, for instance, development, staging and productions, you need different New Relic scripts to inject into the head. Otherwise data from the different environments get mixed and result into non-information.
