### ISSUE TITLE
Unable to run html-webpack-plugin on Windows

### ISSUE THREAD

**Issue by zg** [ampedandwired/html-webpack-plugin#398]
I am trying to use `html-webpack-plugin` on Windows as a dependency for a project I work on. It unfortunately is not working correctly and I'm seeing the following issue arise. Are there any solutions to this issue that can be implemented to circumvent this?

```console
Html Webpack Plugin:
  ReferenceError: window is not defined
  
  - loader.js:3 eval
    C:\users\zack\project\app/index.html?../~/html-webpack-plugin/lib/loader.js:3:1
  
  - index.html:549 Object.
    C:/users/zack/project/app/index.html:549:2
  
  - index.html:519 __webpack_require__
    C:/users/zack/project/app/index.html:519:30
  
  - index.html:542 
    C:/users/zack/project/app/index.html:542:37
  
  - index.html:545 
    C:/users/zack/project/app/index.html:545:10
  
  - index.js:225 HtmlWebpackPlugin.evaluateCompilationResult
    [project]/[html-webpack-plugin]/index.js:225:26
  
  - index.js:115 
    [project]/[html-webpack-plugin]/index.js:115:21
  
  - util.js:16 tryCatcher
    [project]/[html-webpack-plugin]/[bluebird]/js/release/util.js:1    6:23
  
  - promise.js:504 Promise._settlePromiseFromHandler
    [project]/[html-webpack-plugin]/[bluebird]/js/release/promise.j    s:504:31
  
  - promise.js:561 Promise._settlePromise
    [project]/[html-webpack-plugin]/[bluebird]/js/release/promise.j    s:561:18
```

**Comment by jantimon** [comment]
looks like a issue with the style-loader

**Comment by dsebastien** [comment]
I've just noticed that I have the same issue. 
With standard usage (index.html file with <%= template variables) it works fine.

This issue arises for me when I try to use require in the index.html template.

My goal is to split the index.html in multiple files so that I can reuse building blocks.
I'd like the index.html file to contain almost only require statements:

```
<%= require("./header.html"); %>
...
<%= require("./footer.html"); %>
```

**Comment by jantimon** [comment]
The loader occurs because the loader thinks it is in the browser context.. unfortunately that can't be fixed by this plugin.

**Comment by dsebastien** [comment]
Mhh can you give me a bit more context? Is is really the style-loader that causes this issue?
How is it called?

**Comment by jantimon** [comment]
I have no idea as you gave no context ;)
which loader is parsing `./header.html`?

**Comment by dsebastien** [comment]
:)

So my setup is as follows:

* the HtmlWebpackPlugin has the "template" property pointing to the index.html file (https://github.com/dsebastien/angularjs-webpack-starter/blob/master/config/webpack.common.js)
* the index.html file is excluded from the html-loader so that the default templating of HtmlWebpackPlugin is applied
* index.html contains the whole page and uses variables with <%= ... (https://github.com/dsebastien/angularjs-webpack-starter/blob/master/src/index.html)

The above works perfectly.

Now my goal is to split that index.html in multiple files and that's where it breaks.

If I move all the contents of the index.html file to a test.html page right next to it and use <%= require("./test.html"); %> in index.html I get the error described here

The error occurs even if I put "Hello world" in test.html

**Comment by jantimon** [comment]
@sebastienbarre which loader is used for `test.html`?

**Comment by sebastienbarre** [comment]
@jantimon did you mean @dsebastien?

**Comment by dsebastien** [comment]
Good question...
I have configured the html-loader plugin to exclude my index.html, based on the following documentation: https://github.com/ampedandwired/html-webpack-plugin/blob/master/migration.md#loaders-in-templates

If I understood that correctly, it means that the html webpack plugin uses its own mechanism (I guess this? https://github.com/ampedandwired/html-webpack-plugin/blob/master/lib/loader.js)

test.html is not excluded from the html-loader config, but given the above I would assume that the html webpack plugin is in charge of anything that needs to happen while going through index.html

I didn't go any further yet though..

**Comment by jantimon** [comment]
webpack is using loaders for files which are no pure js files. could you please try to use the raw loader?

**Comment by jantimon** [comment]
this plugin compiles the template using your webpack configuration - for index.html it is using a fallback loader if it can't find one.

**Comment by dsebastien** [comment]
Mh okay I'll try to configure a raw-loader to match for ".html-template" and rename the file accordingly to ensure that the html loader is not used for that one.

I'll come back when I have tested this.

A possible workaround might be to use a html-webpack-plugin-specific method for including another file, so that the fallback loader is used just like for the index.html if used.

**Comment by jantimon** [comment]
the webpack api is quite flexible try <%= require("!!raw!test.html") %>

**Comment by dsebastien** [comment]
Hello @jantimon 

I've tried the solution you proposed. The test.html gets loaded, but unfortunately the variables within that file are not processed, which I guess is normal since the raw loader does not know anything about those.

Do you have any other ideas? Ideally I guess that within my index.html, instead of the following: 
```
<%= require("!!raw!test.html") %>
```

Instead I guess I need some sort of requireHtmlWebpackPluginTemplate("test.html");, which would internally: use the raw loader to get the file contents then apply the same interpolation applied to the index.html file by the plugin.

Do you think something like that is doable?

**Comment by jantimon** [comment]
Yes it is
