### ISSUE TITLE
Including apple-touch and other icons in index.html

### ISSUE THREAD

**Issue by nareshbhatia** [ampedandwired/html-webpack-plugin#479]
I am seeing several issues around this but no definitive answer. What is the recommended way to include icon files in the final build? I tried putting the following lines in my index.html template:

    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" href="/favicon-32x32.png" sizes="32x32">
    <link rel="icon" type="image/png" href="/favicon-16x16.png" sizes="16x16">
    <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">

Unfortunately the images are not copied to the output folder.

P.S. I am using Webpack 2.

**Comment by jantimon** [comment]
You can require the images with `<%= require('./apple-touch-icon.png'); %>` but then you also need a loader for the images

**Comment by SoullessWaffle** [comment]
@nareshbhatia If you just want to include icons, you can use the [favicons webpack plugin](https://github.com/jantimon/favicons-webpack-plugin).
It's worked pretty well for me so far, and [it doesn't take much configuration](https://github.com/ProjectTimato/timato-client-web/blob/master/webpack.config.js#L63) to enable it, since (by default) it automatically injects the icons into your generated html.

**Comment by nareshbhatia** [comment]
@jantimon @SoullessWaffle, thanks for your suggestions - all good. I ended up using [copy-webpack-plugin](https://github.com/kevlened/copy-webpack-plugin). It gave me a little more control on what gets copied. My requirements are more than just favicons, I am trying to create a full-fledged manifest.json that allows the app to go offline. That part is still not quite working - it seems that browsers are very finicky about what exactly should go into that file.
